ALTER TABLE customers ALTER COLUMN customer_id TYPE VARCHAR(256), ALTER COLUMN data TYPE VARCHAR;

ALTER TABLE profileimages ALTER COLUMN customer_id TYPE VARCHAR(256), ALTER COLUMN contenttype TYPE VARCHAR(256);
